repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  - repo: local
    hooks:
      - id: no-claude-mentions
        name: Check for Claude mentions
        entry: sh -c 'git diff --cached --name-only -z | xargs -0 grep -l -i -E "claude|anthropic|🤖" || exit 0; if [ $? -eq 0 ]; then echo "Error: Found Claude/Anthropic mentions in staged files. Please remove them."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
      - id: no-claude-in-commit-msg
        name: Check commit message for Claude mentions
        entry: sh -c 'if echo "$1" | grep -i -E "claude|anthropic|🤖|generated with|co-authored-by.*claude" > /dev/null; then echo "Error: Commit message contains Claude/Anthropic mentions. Please remove them."; exit 1; fi'
        language: system
        stages: [commit-msg]
        pass_filenames: false
        always_run: true